# Generated by Django 2.2.5 on 2020-12-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201226_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в замовленні', 'verbose_name_plural': 'Товари в замовленні'},
        ),
    ]
